### ISSUE TITLE
The results of the PURE test are different from those in the paper

### ISSUE THREAD

**Issue by dalaoplan** [CVRL/SiNC-rPPG#4]
After training and testing on PURE, the test results are significantly different from those in the paper，The results I got are shown below，I got the result step by step according to the readme, but I don't know where I made a mistake.  Could you explain why?
----
pure_testing
ME, MAE, RMSE, r
-1.00 $\pm$ 1.26 & 1.75 $\pm$ 1.48 & 5.82 $\pm$ 3.01 & 0.96 $\pm$ 0.03

**Comment by Jemspeth** [comment]
@dalaoplan Based on the large standard deviations and low errors shown here, it looks like maybe 14/15 of your models converged and 1 of the 15 did not. Can you check the performance for each of the models to see? Those results are still quite good overall.
Another potential difference is that we used the [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace) landmarker in the paper rather than MediaPipe. The setup is slightly more tedious than MediaPipe's, which is why I didn't add that code in here.

**Comment by dalaoplan** [comment]
@Jemspeth Thank you for your answer，You are right. I checked and found that the third training only trained for 100 epochs. I retested and got the following results, which were better than the last time. In addition, I have a question. The performance on the DDMP data set is not particularly good, and the results are much worse than the results on the UBFC and PURE data. Why is this? If I continue to want to train on the DDMP dataset, can you provide the preprocessing code? Because the data in DDMP is in `.mat` format, I don't understand how to extract landmarks in this format.


 --- 
the  results
-0.12 $\pm$ 0.09 & 0.73 $\pm$ 0.18 & 3.99 $\pm$ 1.45 & 0.98 $\pm$ 0.01
